export const POST_RATE_LIMIT = 30; // Minimum wait time between posts
export const POST_MAX_CHARS = 200;

export const themes = {
    dark: {
        mainBackground: "#111111",
        card: "#1D1D22",
        text: "#ffffff",
        mediumText: "#e5e5e7",
        lightText: "#cbcbcf",
        profileHover: "#26262a",
        buttonPrimary: "#1D8BFE",
        buttonPrimaryText: "#ffffff",
        buttonPrimaryHoverBackground: "#1873d3",
        buttonPrimaryHoverText: "#ffffff",
        buttonSecondary: "transparent",
        buttonSecondaryText: "#1D8BFE",
        buttonSecondaryBorder: "#1D8BFE",
        buttonSecondaryHoverBackground: "#1A2E4B",
        buttonSecondaryHoverText: "#1D8BFE",
        buttonLink: "transparent",
        buttonLinkText: "#1D8BFE",
        buttonLinkHoverBackground: "transparent",
        buttonLinkHoverText: "#ffffff",
        postBorder: "#1D1D22",
        tooltipBackground: "#1D1D22",
        tooltipBorder: "#4c4c4c",
        snackbarText: "#ffffff",
        snackbarError: "#C92F45",
        snackbarSuccess: "#3bab5b",
    },
    light: {
        mainBackground: "red",
        card: "blue",
        text: "#ffffff",
        lightText: "#cbcbcf",
        profileHover: "#26262a",
        buttonPrimary: "#237BFF",
        buttonSecondary: "#1E1E1E",
        buttonSecondaryBorder: "#cbcbcf",
    },
};
