export const themes = {
    dark: {
        mainBackground: "#111111",
        card: "#1D1D22",
        text: "#ffffff",
        lightText: "#cbcbcf",
        profileHover: "#26262a",
        buttonPrimary: "#1D8BFE",
        buttonPrimaryText: "#ffffff",
        buttonPrimaryHoverBackground: "#1873d3",
        buttonPrimaryHoverText: "#ffffff",
        buttonSecondary: "transparent",
        buttonSecondaryText: "#1D8BFE",
        buttonSecondaryBorder: "#1D8BFE",
        buttonSecondaryHoverBackground: "#1A2E4B",
        buttonSecondaryHoverText: "#1D8BFE",
        postBorder: "#1D1D22",
    },
    light: {
        mainBackground: "red",
        card: "blue",
        text: "#ffffff",
        lightText: "#cbcbcf",
        profileHover: "#26262a",
        buttonPrimary: "#237BFF",
        buttonSecondary: "#1E1E1E",
        buttonSecondaryBorder: "#cbcbcf",
    },
};
